### ISSUE TITLE
Rebar messing the code path

### ISSUE THREAD

**Issue by ddosia** [idubrov/covertool#16]
I have covertool as a dependency, it brings rebar as well.
I have locally installed rebar, which I use to build software.
For some reasons whenever I try to build my project(which depends on covertool), I have weird compilation issues: it puts "deps/rebar" in codepath earlier than my rebar. Thus new rebar calls modules from "deps/rebar" and a lot of "error:undef" as result.
Not quite sure is this problem of rebar? Do you guys have an advice?

**Comment by fp** [comment]
PR #27 is available for merging to fix this issue.

**Comment by fp** [comment]
@ddosia this is not fixed in master!

**Comment by tsloughter** [comment]
Closing as it is a rebar2 specific issue which is a deprecated tool.
